-- Catalog of every selectable MVM mech. Combat code reads these tables; do not stub kits.
local Util = require(script.Parent.Util)

local C = Util.color

local function gun(def)
	return def
end

local MechConfig = {}

MechConfig.Order = {
	"assault",
	"titan",
	"scout",
	"sniper",
	"flame",
	"rocket",
	"guardian",
	"shadow",
	"howitzer",
	"berserker",
}

MechConfig.ById = {
	assault = {
		id = "assault",
		name = "Assault Striker",
		role = "Frontline hybrid",
		blurb = "Balanced rifle fire and shoulder missiles. The default warfighter.",
		armor = 6,
		speed = 6,
		maxHealth = 1250,
		walkSpeed = 30,
		turnRate = 2.6,
		scale = 1,
		color = C(72, 92, 58),
		accent = C(232, 140, 42),
		cockpit = C(30, 40, 36),
		weapons = {
			primary = gun({
				id = "mg",
				name = "20mm Vulcan",
				slot = "primary",
				kind = "hitscan",
				button = "LMB",
				damage = 16,
				rpm = 620,
				range = 320,
				spread = 1.1,
				ammo = 90,
				reload = 2.1,
				tracer = "tracer",
			}),
			secondary = gun({
				id = "missile",
				name = "SRM-6",
				slot = "secondary",
				kind = "projectile",
				button = "RMB",
				damage = 90,
				radius = 14,
				speed = 180,
				lifetime = 3.2,
				cooldown = 2.0,
				ammo = 6,
				reload = 5.5,
				gravity = 0,
			}),
			specialQ = gun({
				id = "overclock",
				name = "Overclock",
				slot = "specialQ",
				kind = "buff",
				button = "Q",
				cooldown = 18,
				duration = 6,
				fireRateMul = 1.35,
				speedMul = 1.12,
			}),
			specialE = gun({
				id = "chaff",
				name = "Chaff Burst",
				slot = "specialE",
				kind = "buff",
				button = "E",
				cooldown = 14,
				duration = 4,
				damageTakenMul = 0.75,
			}),
		},
	},

	titan = {
		id = "titan",
		name = "Heavy Titan",
		role = "Siege armor",
		blurb = "Slow walking fortress. Charge a railgun, then stomp the pad flat.",
		armor = 10,
		speed = 3,
		maxHealth = 2100,
		walkSpeed = 18,
		turnRate = 1.5,
		scale = 1.22,
		color = C(48, 50, 56),
		accent = C(212, 176, 72),
		cockpit = C(20, 20, 24),
		weapons = {
			primary = gun({
				id = "rail",
				name = "120mm Rail",
				slot = "primary",
				kind = "hitscan",
				button = "LMB",
				damage = 175,
				rpm = 38,
				range = 520,
				spread = 0.15,
				ammo = 8,
				reload = 3.4,
				pierce = true,
				tracer = "rail",
			}),
			secondary = gun({
				id = "howl",
				name = "Shoulder Howl",
				slot = "secondary",
				kind = "projectile",
				button = "RMB",
				damage = 80,
				radius = 16,
				speed = 140,
				lifetime = 4,
				cooldown = 2.6,
				ammo = 4,
				reload = 6,
			}),
			specialQ = gun({
				id = "fortress",
				name = "Fortress Stance",
				slot = "specialQ",
				kind = "buff",
				button = "Q",
				cooldown = 20,
				duration = 8,
				damageTakenMul = 0.5,
				speedMul = 0.4,
			}),
			specialE = gun({
				id = "stomp",
				name = "Seismic Stomp",
				slot = "specialE",
				kind = "aoe",
				button = "E",
				damage = 130,
				radius = 30,
				cooldown = 8,
			}),
		},
	},

	scout = {
		id = "scout",
		name = "Scout Runner",
		role = "Harasser",
		blurb = "Light frame, dual SMGs, and a dash that rewrites the engagement range.",
		armor = 3,
		speed = 10,
		maxHealth = 780,
		walkSpeed = 46,
		turnRate = 3.6,
		scale = 0.88,
		color = C(210, 176, 36),
		accent = C(20, 20, 20),
		cockpit = C(28, 24, 12),
		weapons = {
			primary = gun({
				id = "smg",
				name = "Twin Kestrel",
				slot = "primary",
				kind = "hitscan",
				button = "LMB",
				damage = 8,
				rpm = 920,
				range = 180,
				spread = 2.4,
				ammo = 56,
				reload = 1.6,
				tracer = "tracer",
			}),
			secondary = gun({
				id = "burst",
				name = "Scatter Burst",
				slot = "secondary",
				kind = "hitscan",
				button = "RMB",
				damage = 10,
				pellets = 6,
				rpm = 90,
				range = 90,
				spread = 6,
				ammo = 8,
				reload = 2.4,
			}),
			specialQ = gun({
				id = "dash",
				name = "Vector Dash",
				slot = "specialQ",
				kind = "dash",
				button = "Q",
				cooldown = 4.5,
				distance = 55,
			}),
			specialE = gun({
				id = "afterburner",
				name = "Afterburner",
				slot = "specialE",
				kind = "buff",
				button = "E",
				cooldown = 12,
				duration = 4,
				speedMul = 1.85,
			}),
		},
	},

	sniper = {
		id = "sniper",
		name = "Sniper Longshot",
		role = "Overwatch",
		blurb = "Glass cannon. One rail through a cockpit ends the argument.",
		armor = 2,
		speed = 5,
		maxHealth = 620,
		walkSpeed = 26,
		turnRate = 2.1,
		scale = 0.96,
		color = C(36, 58, 92),
		accent = C(120, 210, 255),
		cockpit = C(12, 18, 28),
		weapons = {
			primary = gun({
				id = "longrail",
				name = "Longrail IX",
				slot = "primary",
				kind = "hitscan",
				button = "LMB",
				damage = 210,
				rpm = 28,
				range = 740,
				spread = 0.05,
				ammo = 5,
				reload = 3.8,
				tracer = "rail",
			}),
			secondary = gun({
				id = "spotter",
				name = "Spotter Pulse",
				slot = "secondary",
				kind = "hitscan",
				button = "RMB",
				damage = 35,
				rpm = 70,
				range = 740,
				spread = 0,
				ammo = 12,
				reload = 2.2,
				mark = true,
			}),
			specialQ = gun({
				id = "stabilize",
				name = "Stabilize",
				slot = "specialQ",
				kind = "buff",
				button = "Q",
				cooldown = 16,
				duration = 5,
				damageMul = 1.25,
				speedMul = 0.55,
			}),
			specialE = gun({
				id = "ghost",
				name = "Ghost Shroud",
				slot = "specialE",
				kind = "cloak",
				button = "E",
				cooldown = 18,
				duration = 2.4,
			}),
		},
	},

	flame = {
		id = "flame",
		name = "Flame Siege",
		role = "Area denial",
		blurb = "Walks the lane shut. Cone fire and napalm that outlives the trigger pull.",
		armor = 7,
		speed = 4,
		maxHealth = 1500,
		walkSpeed = 22,
		turnRate = 1.8,
		scale = 1.08,
		color = C(92, 28, 22),
		accent = C(255, 120, 32),
		cockpit = C(30, 12, 10),
		weapons = {
			primary = gun({
				id = "flamer",
				name = "Napalm Throat",
				slot = "primary",
				kind = "cone",
				button = "LMB",
				damage = 14,
				rpm = 400,
				range = 46,
				angle = 28,
				ammo = 120,
				reload = 2.8,
			}),
			secondary = gun({
				id = "napalm",
				name = "Gel Canister",
				slot = "secondary",
				kind = "projectile",
				button = "RMB",
				damage = 40,
				radius = 18,
				speed = 90,
				lifetime = 3,
				cooldown = 3.2,
				ammo = 4,
				reload = 5,
				linger = 5,
				lingerDps = 18,
			}),
			specialQ = gun({
				id = "inferno",
				name = "Inferno Surge",
				slot = "specialQ",
				kind = "cone",
				button = "Q",
				damage = 28,
				rpm = 60,
				range = 58,
				angle = 42,
				cooldown = 10,
				ammo = 1,
				reload = 10,
			}),
			specialE = gun({
				id = "firewall",
				name = "Firewall",
				slot = "specialE",
				kind = "aoe",
				button = "E",
				damage = 55,
				radius = 22,
				cooldown = 12,
				linger = 6,
				lingerDps = 12,
			}),
		},
	},

	rocket = {
		id = "rocket",
		name = "Rocket Barrage",
		role = "Saturation",
		blurb = "Paints up to four locks, then empties the racks. Reload is the tax.",
		armor = 5,
		speed = 5,
		maxHealth = 1100,
		walkSpeed = 27,
		turnRate = 2.2,
		scale = 1.04,
		color = C(78, 86, 52),
		accent = C(190, 210, 80),
		cockpit = C(24, 28, 16),
		weapons = {
			primary = gun({
				id = "lockrockets",
				name = "MLRS Pods",
				slot = "primary",
				kind = "lockon",
				button = "LMB",
				damage = 48,
				radius = 10,
				speed = 160,
				lifetime = 4,
				maxLocks = 4,
				lockRange = 360,
				ammo = 16,
				reload = 4.5,
				cooldown = 1.6,
			}),
			secondary = gun({
				id = "dumbfire",
				name = "Dumbfire Salvo",
				slot = "secondary",
				kind = "projectile",
				button = "RMB",
				damage = 36,
				radius = 9,
				speed = 150,
				lifetime = 2.6,
				count = 5,
				spread = 8,
				cooldown = 3.5,
				ammo = 10,
				reload = 5,
			}),
			specialQ = gun({
				id = "paint",
				name = "Target Paint",
				slot = "specialQ",
				kind = "buff",
				button = "Q",
				cooldown = 14,
				duration = 6,
				lockBonus = 2,
			}),
			specialE = gun({
				id = "hotswap",
				name = "Hot-Swap Racks",
				slot = "specialE",
				kind = "reload",
				button = "E",
				cooldown = 16,
			}),
		},
	},

	guardian = {
		id = "guardian",
		name = "Shield Guardian",
		role = "Anchor",
		blurb = "Energy shield up front, pulse cannon behind it. Holds a pad.",
		armor = 8,
		speed = 4,
		maxHealth = 1600,
		walkSpeed = 23,
		turnRate = 1.9,
		scale = 1.12,
		color = C(228, 232, 240),
		accent = C(64, 196, 230),
		cockpit = C(20, 32, 40),
		weapons = {
			primary = gun({
				id = "pulse",
				name = "Pulse Cannon",
				slot = "primary",
				kind = "hitscan",
				button = "LMB",
				damage = 38,
				rpm = 210,
				range = 280,
				spread = 0.6,
				ammo = 24,
				reload = 2.0,
				tracer = "pulse",
			}),
			secondary = gun({
				id = "shield",
				name = "Aegis Face",
				slot = "secondary",
				kind = "shield",
				button = "RMB",
				cooldown = 11,
				duration = 5,
				damageTakenMul = 0.25,
				frontal = true,
			}),
			specialQ = gun({
				id = "dome",
				name = "Barrier Dome",
				slot = "specialQ",
				kind = "buff",
				button = "Q",
				cooldown = 18,
				duration = 6,
				damageTakenMul = 0.55,
			}),
			specialE = gun({
				id = "nova",
				name = "Pulse Nova",
				slot = "specialE",
				kind = "aoe",
				button = "E",
				damage = 70,
				radius = 26,
				cooldown = 10,
				knockback = 70,
			}),
		},
	},

	shadow = {
		id = "shadow",
		name = "Stealth Shadow",
		role = "Assassin",
		blurb = "Cloak in, burst shotgun or dagger, cloak out. Loses the argument at range.",
		armor = 3,
		speed = 8,
		maxHealth = 820,
		walkSpeed = 38,
		turnRate = 3.2,
		scale = 0.9,
		color = C(18, 16, 28),
		accent = C(164, 72, 220),
		cockpit = C(10, 8, 16),
		weapons = {
			primary = gun({
				id = "shotgun",
				name = "Burst Shroud",
				slot = "primary",
				kind = "hitscan",
				button = "LMB",
				damage = 14,
				pellets = 8,
				rpm = 75,
				range = 48,
				spread = 7,
				ammo = 6,
				reload = 2.3,
				decloak = true,
			}),
			secondary = gun({
				id = "dagger",
				name = "Plasma Dagger",
				slot = "secondary",
				kind = "melee",
				button = "RMB",
				damage = 95,
				range = 16,
				cooldown = 1.5,
				lunge = 22,
			}),
			specialQ = gun({
				id = "cloak",
				name = "Optical Cloak",
				slot = "specialQ",
				kind = "cloak",
				button = "Q",
				cooldown = 12,
				duration = 6,
			}),
			specialE = gun({
				id = "blink",
				name = "Blink",
				slot = "specialE",
				kind = "dash",
				button = "E",
				cooldown = 7,
				distance = 42,
			}),
		},
	},

	howitzer = {
		id = "howitzer",
		name = "Artillery Howitzer",
		role = "Indirect fire",
		blurb = "Arcing mortar that owns open ground. Bracing the gun almost stops the legs.",
		armor = 6,
		speed = 3,
		maxHealth = 1180,
		walkSpeed = 20,
		turnRate = 1.4,
		scale = 1.14,
		color = C(96, 68, 40),
		accent = C(230, 120, 40),
		cockpit = C(28, 20, 12),
		weapons = {
			primary = gun({
				id = "mortar",
				name = "210mm Mortar",
				slot = "primary",
				kind = "mortar",
				button = "LMB",
				damage = 150,
				radius = 20,
				speed = 110,
				arc = 0.55,
				lifetime = 5,
				ammo = 6,
				reload = 3.6,
				firingSlow = 0.2,
				slowHold = 0.7,
			}),
			secondary = gun({
				id = "cluster",
				name = "Cluster Shell",
				slot = "secondary",
				kind = "mortar",
				button = "RMB",
				damage = 42,
				radius = 12,
				speed = 105,
				arc = 0.5,
				count = 4,
				spread = 14,
				lifetime = 5,
				ammo = 4,
				reload = 5.2,
				firingSlow = 0.2,
				cooldown = 3.0,
			}),
			specialQ = gun({
				id = "brace",
				name = "Deploy Braces",
				slot = "specialQ",
				kind = "buff",
				button = "Q",
				cooldown = 16,
				duration = 8,
				speedMul = 0.08,
				damageMul = 1.3,
			}),
			specialE = gun({
				id = "smoke",
				name = "Smoke Screen",
				slot = "specialE",
				kind = "aoe",
				button = "E",
				damage = 0,
				radius = 28,
				cooldown = 14,
				linger = 7,
				obscure = true,
			}),
		},
	},

	berserker = {
		id = "berserker",
		name = "Berserker Claw",
		role = "Brawler",
		blurb = "No polite range. Claws, axe, and a bloodlust sprint into the cockpit.",
		armor = 5,
		speed = 7,
		maxHealth = 1350,
		walkSpeed = 34,
		turnRate = 3.0,
		scale = 1.02,
		color = C(140, 24, 28),
		accent = C(255, 196, 64),
		cockpit = C(32, 8, 10),
		weapons = {
			primary = gun({
				id = "claws",
				name = "Twin Rippers",
				slot = "primary",
				kind = "melee",
				button = "LMB",
				damage = 48,
				range = 18,
				rpm = 160,
				ammo = 30,
				reload = 1.4,
			}),
			secondary = gun({
				id = "axe",
				name = "Sever Axe",
				slot = "secondary",
				kind = "aoe",
				button = "RMB",
				damage = 110,
				radius = 20,
				cooldown = 2.8,
				ammo = 4,
				reload = 4,
			}),
			specialQ = gun({
				id = "bloodlust",
				name = "Bloodlust",
				slot = "specialQ",
				kind = "buff",
				button = "Q",
				cooldown = 16,
				duration = 7,
				speedMul = 1.35,
				lifesteal = 0.35,
				damageMul = 1.15,
			}),
			specialE = gun({
				id = "rush",
				name = "Charge Rush",
				slot = "specialE",
				kind = "dash",
				button = "E",
				cooldown = 8,
				distance = 48,
				damage = 60,
				radius = 12,
			}),
		},
	},
}

function MechConfig.get(id)
	return MechConfig.ById[id]
end

function MechConfig.list()
	local rows = {}
	for _, id in ipairs(MechConfig.Order) do
		table.insert(rows, MechConfig.ById[id])
	end
	return rows
end

function MechConfig.weapon(mechId, slot)
	local mech = MechConfig.ById[mechId]
	if not mech then
		return nil
	end
	return mech.weapons[slot]
end

return MechConfig
